config/routes.rb
Rails.application.routes.draw do

  resources :user_events
  devise_for :users, controllers: {
    registrations: 'registrations'
  }

  root 'group_events#index'
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :user_events
end

app/models/user_event.rb
class UserEvent < ActiveRecord::Base

validate :check_presence_of_start_end_and_duration
# validates :start_date, format: { with: /\A\d{4}-\d{2}-\d{2}\z/ }, allow_nil: true
belongs_to :user


	def check_presence_of_start_end_and_duration			
		  if start_date.present? && end_date.present? && duration.present?
		      no_of_days = (start_date..end_date).count
		      errors.add(:duration, "no of duration days is incorrect") if no_of_days != duration
		  elsif start_date.present? && !end_date.present? && !duration.present?
		      errors.add(:base, "either end date or duration should be present")
		  elsif !start_date.present? && end_date.present? && !duration.present?
		      errors.add(:base, "either end date or duration should be present")
		  elsif !start_date.present? && !end_date.present? && duration.present?
		      errors.add(:base, "either end date or duration should be present")
		  else
		      errors.add(:base, "please enter any two out of start date, end date and duration")
		  end
	end

	def self.field_values_calculation(params)
		if !params[:user_event][:start_date].present?
        params[:user_event][:start_date] = params[:user_event][:end_date].to_date - params[:user_event][:duration].to_i+1
      elsif !params[:user_event][:end_date].present?
        params[:user_event][:end_date] = params[:user_event][:start_date].to_date + params[:user_event][:duration].to_i-1
      elsif !params[:user_event][:duration].present?
        params[:user_event][:duration] = (params[:user_event][:start_date].to_date..params[:user_event][:end_date].to_date).count
      else
        params
      end
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :set_user_id

  def set_user_id
  	@user = current_user
  end

end

app/controllers/group_events_controller.rb
class GroupEventsController < ApplicationController
	def index
	end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

	  def sign_up_params
	    params.require(:user).permit(:name, :email, :password, :password_confirmation)
	  end 

	  def account_update_params
	    params.require(:user).permit(:name, :email, :password, :password_confirmation, :current_password)
	  end
end

app/controllers/user_events_controller.rb
class UserEventsController < ApplicationController
  before_action :set_user_event, only: [:show, :edit, :update, :destroy]
  before_action :set_all_fields, only: [:create, :update]

  # GET /user_events
  # GET /user_events.json
  def index
    @user_events = @user.user_events.where.not(status: "ND")
  end

  # GET /user_events/1
  # GET /user_events/1.json
  def show
  end

  # GET /user_events/new
  def new
    @user_event = @user.user_events.new
  end

  # GET /user_events/1/edit
  def edit
  end

  # POST /user_events
  # POST /user_events.json
  def create
    @user_event = @user.user_events.new(user_event_params)

    respond_to do |format|
      if @user_event.save
        format.html { redirect_to @user_event, notice: 'User event was successfully created.' }
        format.json { render :show, status: :created, location: @user_event }
      else
        format.html { render :new }
        format.json { render json: @user_event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_events/1
  # PATCH/PUT /user_events/1.json
  def update
    respond_to do |format|
      if @user_event.update(user_event_params)
        format.html { redirect_to @user_event, notice: 'User event was successfully updated.' }
        format.json { render :show, status: :ok, location: @user_event }
      else
        format.html { render :edit }
        format.json { render json: @user_event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_events/1
  # DELETE /user_events/1.json
  def destroy
    if @user_event.status == "D"
      @user_event.destroy
    else
      @user_event.update!(status: "ND")
    end
    respond_to do |format|
      format.html { redirect_to user_events_url, notice: 'User event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_event
      @user_event = @user.user_events.where(id: params[:id]).first
    end

    def set_all_fields
      UserEvent.field_values_calculation(params)
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_event_params
      params.require(:user_event).permit(:name, :description, :location, :start_date, :end_date, :duration, :status)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def resource_class
    User
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/helpers/group_events_helper.rb
module GroupEventsHelper
end

app/helpers/user_events_helper.rb
module UserEventsHelper
end

app/views/group_events/index.html.erb
<% if user_signed_in? %>
<h1 class="title is-5">Welcome, <%= current_user.name %>!</h1>
<%= link_to "View Events", user_events_path, class:"button is-info" %>
<% else %>

<%= render "shared/login_form" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Users Event</title>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag 'https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css' %>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application' %>
</head>

<body class="<%= yield (:body_class) %>">
  <% if flash[:notice] %>
  <div class="notification is-success global-notification">
    <p class="notice"><%= notice %></p>
  </div>
  <% end %>
  <% if flash[:alert] %>
  <div class="notification is-danger global-notification">
    <p class="alert"><%= alert %></p>
  </div>
  <% end %>
  <nav class="navbar is-warning" role="navigation" aria-label="main navigation">
    <div class="navbar-brand">
      <%= link_to root_path, class:"navbar-item" do %>
      <h1 class="title is-5">Users Event</h1>
      <% end  %>
      <div class="navbar-burger burger" data-target="navbar">
        <span></span>
        <span></span>
        <span></span>
      </div>
    </div>

    <div id="navbar" class="navbar-menu">
      <div class="navbar-end">
        <div class="navbar-item">
          <div class="field is-grouped">

            <% if user_signed_in? %>
            <div class="navbar-item has-dropdown is-hoverable">
              <%= link_to 'Account', edit_user_registration_path, class: "navbar-link" %>
              <div class="navbar-dropdown is-right">
                <%= link_to "Edit Your Details", edit_user_registration_path,  class: "navbar-item" %>
                <%= link_to "Log Out", destroy_user_session_path, method: :delete, class:"navbar-item" %>
              </div>
            </div>
            <% else %>

            <%= link_to "Sign In", new_user_session_path, class:"navbar-item button is-warning" %>
            <%= link_to "Sign up", new_user_registration_path, class:"navbar-item button is-warning"%>

            <% end %>
          </div>
        </div>
      </div>
    </div>
  </nav>

  <%= yield(:header) %>
    <div class="container">
  <%= yield %>
  </div>

</body>
</html>

app/views/shared/_login_form.html.erb
<section class="section">
    <div class="container">
        <div class="columns is-centered">
            <div class="column is-4">
                <h2 class="title is-2">Log in</h2>
                <%= simple_form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>

                  <div class="field">
                      <div class="control">
                        <%= f.input :email, required: false, input_html: { class: "input"}, wrapper: false, label_html: { class: "label" } %>
                    </div>
                  </div>

                  <div class="field">
                      <div class="control">
                    <%= f.input :password, required: false, input_html: { class: "input"}, wrapper: false, label_html: { class: "label" } %>
                        </div>
                    </div>

                    <div class="field">
                      <div class="control">
                    <%= f.input :remember_me, wrapper: false, as: :boolean if devise_mapping.rememberable? %>
                      </div>
                    </div>

                  <%= f.button :submit, "Log in", class:"button is-info" %>
                <% end %>
                <br/>
                <%= render "devise/shared/links" %>
            </div>
        </div>
    </div>
</section>

app/views/user_events/_form.html.erb
<%= simple_form_for(@user_event) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :description %>
    <%= f.input :location %>
    <%= f.input :start_date, placeholder: "yyyy-mm-dd" %>
    <%= f.input :end_date, placeholder: "yyyy-mm-dd" %>
    <%= f.input :duration %>
    Do you want to save as draft or pubish?<br><%= f.select :status, [["Draft","D"], ["Publish", "P"]] %>
  </div><br>

  <div class="form-actions">
    <%= f.button :submit, class:"button is-success" %>
  </div>
<% end %>

app/views/user_events/edit.html.erb
<h1>Editing User Event</h1><br>

<%= render 'form', user_event: @user_event %><br>

<%= link_to 'Show', @user_event, class:"button is-dark" %> |
<%= link_to 'Back', user_events_path, class:"button is-dark" %>

app/views/user_events/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing User Events</h1>

<table class="table is-fullwidth">
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Location</th>
      <th>Start date</th>
      <th>End date</th>
      <th>Duration</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @user_events.each do |user_event| %>
      <tr>
        <td><%= user_event.name %></td>
        <td><%= user_event.description %></td>
        <td><%= user_event.location %></td>
        <td><%= user_event.start_date %></td>
        <td><%= user_event.end_date %></td>
        <td><%= user_event.duration %></td>
        <td><%= link_to 'Show', user_event, class:"button is-link"%></td>
        <td><%= link_to 'Edit', edit_user_event_path(user_event), class:"button is-link" %></td>
        <td><%= link_to 'Destroy', user_event, method: :delete, data: { confirm: 'Are you sure?' }, class:"button is-danger" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User event', new_user_event_path, class:"button is-info" %>

app/views/user_events/new.html.erb
<h1>New User Event</h1><br>

<%= render 'form',user_event: @user_event %><br>

<%= link_to 'Back', user_events_path, class:"button is-dark" %>

app/views/user_events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user_event.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @user_event.description %>
</p>

<p>
  <strong>Location:</strong>
  <%= @user_event.location %>
</p>

<p>
  <strong>Start date:</strong>
  <%= @user_event.start_date %>
</p>

<p>
  <strong>End date:</strong>
  <%= @user_event.end_date %>
</p>

<p>
  <strong>Duration:</strong>
  <%= @user_event.duration %>
</p>

<%= link_to 'Edit', edit_user_event_path(@user_event), class:"button is-dark" %> |
<%= link_to 'Back', user_events_path, class:"button is-dark" %>